import { registerAs } from '@nestjs/config';
import {
  DEFAULT_NODE_ENV,
  DEFAULT_PORT,
  DEFAULT_DB_HOST,
  DEFAULT_DB_PORT,
  DEFAULT_DB_USERNAME,
  DEFAULT_DB_PASSWORD,
  DEFAULT_DB_DATABASE,
  DEFAULT_JWT_SECRET,
  DEFAULT_JWT_EXPIRES_IN,
  DEFAULT_JWT_REFRESH_SECRET,
  DEFAULT_JWT_REFRESH_EXPIRES_IN,
  DEFAULT_CORS_ORIGIN,
  DEFAULT_THROTTLE_TTL,
  DEFAULT_THROTTLE_LIMIT,
  DEFAULT_MAX_FILE_SIZE,
  DEFAULT_UPLOAD_PATH,
  DEFAULT_GEMINI_API_KEY,
  DEFAULT_GEMINI_API_URL,
  DEFAULT_LOG_LEVEL,
  DEFAULT_LOG_FILE,
  DEFAULT_CSRF_ENABLED,
  DEFAULT_HELMET_ENABLED,
  DEFAULT_STRIPE_SECRET_KEY,
  DEFAULT_STRIPE_WEBHOOK_SECRET,
  DEFAULT_REDIS_HOST,
  DEFAULT_REDIS_PORT,
  DEFAULT_REDIS_DB,
  DEFAULT_REDIS_DEFAULT_TTL,
  DEFAULT_REDIS_MAX_ITEMS,
  DEFAULT_STORAGE_PROVIDER,
  DEFAULT_S3_BUCKET,
  DEFAULT_S3_REGION,
  DEFAULT_S3_ACCESS_KEY_ID,
  DEFAULT_S3_SECRET_ACCESS_KEY,
  DEFAULT_CLOUDINARY_CLOUD_NAME,
  DEFAULT_CLOUDINARY_API_KEY,
  DEFAULT_CLOUDINARY_API_SECRET,
  DEFAULT_BASE_URL,
} from '../../common/constants/config.constants';

export default registerAs('app', () => ({
  nodeEnv: process.env.NODE_ENV || DEFAULT_NODE_ENV,
  port: parseInt(process.env.PORT, 10) || DEFAULT_PORT,
  database: {
    host: process.env.DB_HOST || DEFAULT_DB_HOST,
    port: parseInt(process.env.DB_PORT, 10) || DEFAULT_DB_PORT,
    username: process.env.DB_USERNAME || DEFAULT_DB_USERNAME,
    password: process.env.DB_PASSWORD || DEFAULT_DB_PASSWORD,
    database: process.env.DB_DATABASE || DEFAULT_DB_DATABASE,
  },
  jwt: {
    secret: process.env.JWT_SECRET || DEFAULT_JWT_SECRET,
    expiresIn: process.env.JWT_EXPIRES_IN || DEFAULT_JWT_EXPIRES_IN,
    refreshSecret: process.env.JWT_REFRESH_SECRET || DEFAULT_JWT_REFRESH_SECRET,
    refreshExpiresIn: process.env.JWT_REFRESH_EXPIRES_IN || DEFAULT_JWT_REFRESH_EXPIRES_IN,
  },
  cors: {
    origin: process.env.CORS_ORIGIN?.split(',') || [DEFAULT_CORS_ORIGIN],
  },
  throttle: {
    ttl: parseInt(process.env.THROTTLE_TTL, 10) || DEFAULT_THROTTLE_TTL,
    limit: parseInt(process.env.THROTTLE_LIMIT, 10) || DEFAULT_THROTTLE_LIMIT,
  },
  upload: {
    maxFileSize: parseInt(process.env.MAX_FILE_SIZE, 10) || DEFAULT_MAX_FILE_SIZE, // 10MB
    path: process.env.UPLOAD_PATH || DEFAULT_UPLOAD_PATH,
  },
  gemini: {
    apiKey: process.env.GEMINI_API_KEY || DEFAULT_GEMINI_API_KEY,
    apiUrl: process.env.GEMINI_API_URL || DEFAULT_GEMINI_API_URL,
  },
  logging: {
    level: process.env.LOG_LEVEL || DEFAULT_LOG_LEVEL,
    file: process.env.LOG_FILE || DEFAULT_LOG_FILE,
  },
  security: {
    csrfEnabled: process.env.CSRF_ENABLED === 'true' || DEFAULT_CSRF_ENABLED,
    helmetEnabled: process.env.HELMET_ENABLED !== 'false' || DEFAULT_HELMET_ENABLED,
  },
  stripe: {
    secretKey: process.env.STRIPE_SECRET_KEY || DEFAULT_STRIPE_SECRET_KEY,
    webhookSecret: process.env.STRIPE_WEBHOOK_SECRET || DEFAULT_STRIPE_WEBHOOK_SECRET,
  },
  redis: {
    host: process.env.REDIS_HOST || DEFAULT_REDIS_HOST,
    port: parseInt(process.env.REDIS_PORT, 10) || DEFAULT_REDIS_PORT,
    password: process.env.REDIS_PASSWORD,
    db: parseInt(process.env.REDIS_DB, 10) || DEFAULT_REDIS_DB,
    defaultTtl: parseInt(process.env.REDIS_DEFAULT_TTL, 10) || DEFAULT_REDIS_DEFAULT_TTL,
    maxItems: parseInt(process.env.REDIS_MAX_ITEMS, 10) || DEFAULT_REDIS_MAX_ITEMS,
  },
  storage: {
    provider: process.env.STORAGE_PROVIDER || DEFAULT_STORAGE_PROVIDER,
    s3: {
      bucket: process.env.S3_BUCKET || DEFAULT_S3_BUCKET,
      region: process.env.S3_REGION || DEFAULT_S3_REGION,
      accessKeyId: process.env.S3_ACCESS_KEY_ID || DEFAULT_S3_ACCESS_KEY_ID,
      secretAccessKey: process.env.S3_SECRET_ACCESS_KEY || DEFAULT_S3_SECRET_ACCESS_KEY,
    },
    cloudinary: {
      cloudName: process.env.CLOUDINARY_CLOUD_NAME || DEFAULT_CLOUDINARY_CLOUD_NAME,
      apiKey: process.env.CLOUDINARY_API_KEY || DEFAULT_CLOUDINARY_API_KEY,
      apiSecret: process.env.CLOUDINARY_API_SECRET || DEFAULT_CLOUDINARY_API_SECRET,
    },
  },
  baseUrl: process.env.BASE_URL || DEFAULT_BASE_URL,
}));
